# Generated by Django 5.2.7 on 2025-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('genre', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], max_length=1)),
                ('interest', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], max_length=1)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
